### ISSUE TITLE
Context and/or dependencies?

### ISSUE THREAD

**Issue by Spiritdude** [smalyshev/wdq2sparql#7]
I cloned the repo, and tried to run `php w2s_cli.php tests/data/wikidata/1` and it complains about missing `vendor/autoload.php`.

What is the context or the dependencies to get it to work?

**Comment by Spiritdude** [comment]
Got it to work.

Perhaps it would be good to add install instructions in README.md, e.g. `composer` from https://getcomposer.org/download/ and running `php composer.phar install` in the main dir.

**Comment by smalyshev** [comment]
Yes, you need to install composer deps.
